### ISSUE TITLE
The submission guideline/portal is not available...

### ISSUE THREAD

**Issue by zhimin-z** [domaineval/DomainEval#1]
![image](https://github.com/user-attachments/assets/a93e9786-17e6-4ef9-a2ab-7fe2fc7eda6a)
I check this submission URL above but found there is no submission portal for evaluation results...
<img width="1166" alt="image" src="https://github.com/user-attachments/assets/ca19b5b1-5a51-41a5-9413-953a51d3b251">
<img width="470" alt="image" src="https://github.com/user-attachments/assets/5ae4a41f-4492-4c72-a8e1-f2ea8259bccc">

**Comment by domaineval** [comment]
Thanks for reporting this issue! The submission guideline has been updated in README.md

**Comment by zhimin-z** [comment]
> Thanks for reporting this issue! The submission guideline has been updated in README.md

Thanks!
